### ISSUE TITLE
Pleas quickly review my README markdown

### ISSUE THREAD

**Issue by sspnyc** [sspnyc/Project-3#2]
Hi Fritz,
Would like your thoughts. Leaving for lunch in minute.
- Simmy

**Comment by andrewfritz86** [comment]
Looks good and very well thought out. Do you have an ERD yet?

**Comment by sspnyc** [comment]
No I don't. Will complete it when I get back from lunch.

**Comment by andrewfritz86** [comment]
Sounds good!

**Comment by sspnyc** [comment]
Okay did it finally. Check it.

**Comment by andrewfritz86** [comment]
Looks good, for planner_id, you can just use an integer there, you don't actually have to label it as a foreign key.

**Comment by sspnyc** [comment]
ok
